### ISSUE TITLE
 [259196] Failed to execute script 'SteamAutoFriend' due to unhandled exception!

### ISSUE THREAD

**Issue by minein4** [pebnn/SteamAutoFriend#5]
Hello!

Was going to use this program and after inputting the account details the program crashes

Traceback (most recent call last):
  File "SteamAutoFriend.py", line 311, in <module>
  File "selenium\webdriver\remote\webdriver.py", line 665, in find_element_by_name
  File "selenium\webdriver\remote\webdriver.py", line 1248, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 425, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="username"]"}
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
        Ordinal0 [0x00CE1ED3+2236115]
        Ordinal0 [0x00C792F1+1807089]
        Ordinal0 [0x00B866FD+812797]
        Ordinal0 [0x00BB55DF+1005023]
        Ordinal0 [0x00BB57CB+1005515]
        Ordinal0 [0x00BE7632+1209906]
        Ordinal0 [0x00BD1AD4+1120980]
        Ordinal0 [0x00BE59E2+1202658]
        Ordinal0 [0x00BD18A6+1120422]
        Ordinal0 [0x00BAA73D+960317]
        Ordinal0 [0x00BAB71F+964383]
        GetHandleVerifier [0x00F8E7E2+2743074]
        GetHandleVerifier [0x00F808D4+2685972]
        GetHandleVerifier [0x00D72BAA+532202]
        GetHandleVerifier [0x00D71990+527568]
        Ordinal0 [0x00C8080C+1837068]
        Ordinal0 [0x00C84CD8+1854680]
        Ordinal0 [0x00C84DC5+1854917]
        Ordinal0 [0x00C8ED64+1895780]
        BaseThreadInitThunk [0x7625FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77B67B5E+286]
        RtlGetAppContainerNamedObjectPath [0x77B67B2E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SteamAutoFriend.py", line 316, in <module>
  File "selenium\webdriver\remote\webelement.py", line 540, in send_keys
  File "selenium\webdriver\remote\webelement.py", line 710, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 425, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=106.0.5249.119)
Stacktrace:
Backtrace:
        Ordinal0 [0x00CE1ED3+2236115]
        Ordinal0 [0x00C792F1+1807089]
        Ordinal0 [0x00B865C0+812480]
        Ordinal0 [0x00BB0C0E+986126]
        Ordinal0 [0x00BB031D+983837]
        Ordinal0 [0x00BD1A8C+1120908]
        Ordinal0 [0x00BABD84+966020]
        Ordinal0 [0x00BD1CA4+1121444]
        Ordinal0 [0x00BE59E2+1202658]
        Ordinal0 [0x00BD18A6+1120422]
        Ordinal0 [0x00BAA73D+960317]
        Ordinal0 [0x00BAB71F+964383]
        GetHandleVerifier [0x00F8E7E2+2743074]
        GetHandleVerifier [0x00F808D4+2685972]
        GetHandleVerifier [0x00D72BAA+532202]
        GetHandleVerifier [0x00D71990+527568]
        Ordinal0 [0x00C8080C+1837068]
        Ordinal0 [0x00C84CD8+1854680]
        Ordinal0 [0x00C84DC5+1854917]
        Ordinal0 [0x00C8ED64+1895780]
        BaseThreadInitThunk [0x7625FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77B67B5E+286]
        RtlGetAppContainerNamedObjectPath [0x77B67B2E+238]

[259196] Failed to execute script 'SteamAutoFriend' due to unhandled exception!

**Comment by pebnn** [comment]
This issue has been fixed in the latest 1.3.3 version :)

the issue was that Valve updated their login page, this changed the class names used in older versions that was being used to detect the input fields for both username and password. Thanks for submitting your issue :)
